// Run from the Playwright CLI or the existing browser CI job; no separate test framework.
export default async (page) => {
  const browser=page.context().browser(), base=new URL('/studio/',page.url()).href;
  const assert=(v,message)=>{if(!v)throw new Error(message);};
  const contexts=[], errors=[], checks=[];
  async function fresh(options={}){const context=await browser.newContext(options);contexts.push(context);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}
  const desktop=await fresh({viewport:{width:1440,height:900},deviceScaleFactor:1});
  desktop.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  desktop.on('response',r=>{if(r.status()>=400&&new URL(r.url()).origin===new URL(base).origin)errors.push(`${r.status()} ${r.url()}`);});
  await desktop.goto(base);await desktop.waitForFunction(()=>window.__STUDIO_HERO?.active);
  await desktop.waitForFunction(()=>window.__STUDIO_HERO.triangles>100000);
  assert(await desktop.evaluate(()=>window.__STUDIO_HERO.drawCalls<=22),'Bike draw submissions exceeded the joined-material budget');
  assert(await desktop.locator('.project-card').count()===6,'Desktop catalogue incomplete');
  await desktop.screenshot({path:'output/playwright/portfolio-desktop.png'});
  await desktop.getByRole('button',{name:'Use still image'}).click();assert(await desktop.locator('.hero-poster').isVisible(),'Still-image control failed');
  await desktop.getByRole('button',{name:'Explore in 3D',exact:true}).click();assert(await desktop.locator('#bike-canvas').isVisible(),'3D reactivation failed');
  await desktop.getByRole('button',{name:'Research systems',exact:true}).click();
  assert(await desktop.locator('.project-card:visible').count()===1,'Category filtering failed');
  assert(await desktop.locator('#project-count').innerText()==='1 project','Counter mismatch');
  await desktop.getByRole('searchbox',{name:'Search projects'}).fill('no match expected');
  assert(await desktop.locator('.project-card:visible').count()===0&&await desktop.locator('#no-results').isVisible(),'Empty state failed');
  await desktop.getByRole('button',{name:'Clear filters'}).click();assert(await desktop.locator('.project-card:visible').count()===6,'Filter reset failed');
  await desktop.locator('.project-card').first().getByRole('link').click();
  assert(await desktop.locator('h1').innerText()==='Konam','Case study routing failed');
  await desktop.screenshot({path:'output/playwright/portfolio-case-study.png',fullPage:true});
  checks.push('Desktop hero, still toggle, category/search/reset and case study navigation');
  const mobile=await fresh({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await mobile.goto(base+'mobile/');await mobile.waitForFunction(()=>window.__STUDIO_HERO?.active);
  assert(await mobile.evaluate(()=>matchMedia('(pointer: coarse)').matches),'Mobile test lacks real touch');
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');
  for (const card of await mobile.locator('.project-card').all()) { await card.scrollIntoViewIfNeeded(); await card.locator('img').evaluate(img=>img.decode()); }
  await mobile.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
  await mobile.screenshot({path:'output/playwright/portfolio-mobile.png',fullPage:true});
  await mobile.getByRole('button',{name:'3D experiences',exact:true}).click();
  assert(await mobile.locator('.project-card:visible').count()===3&&await mobile.locator('#project-count').innerText()==='3 projects','Touch filtering mismatch');
  await mobile.goto(base+'mobile/archive.html');await mobile.getByRole('button',{name:'Light & Luxury',exact:true}).click();
  assert(await mobile.locator('.work:visible').count()===3,'Legacy archive filter still shows hidden cards');
  checks.push('390px touch entry, mobile LOD, overflow and archive filtering');
  const nojs=await fresh({viewport:{width:1440,height:900},javaScriptEnabled:false});
  await nojs.goto(base);assert(await nojs.locator('.project-card:visible').count()===6,'No-JS catalogue missing');
  assert(await nojs.locator('.hero-poster').isVisible(),'No-JS poster missing');
  await nojs.locator('.project-card').nth(1).getByRole('link').click();assert(await nojs.locator('h1').innerText()==='NOEMA','No-JS case study navigation failed');
  const reduced=await fresh({viewport:{width:390,height:844},reducedMotion:'reduce',isMobile:true,hasTouch:true});
  const reducedModels=[];reduced.on('request',r=>{if(r.url().endsWith('.glb'))reducedModels.push(r.url());});
  await reduced.goto(base,{waitUntil:'networkidle'});assert(reducedModels.length===0,'Reduced motion automatically loaded 3D');
  assert(await reduced.locator('.hero-poster').isVisible(),'Reduced-motion poster missing');
  await reduced.screenshot({path:'output/playwright/portfolio-reduced-motion.png'});
  const noGL=await fresh({viewport:{width:390,height:844}});
  await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/.test(type)?null:original.call(this,type,...args);};});
  await noGL.goto(base);await noGL.waitForFunction(()=>document.getElementById('bike-status').textContent.includes('could not load'));
  assert(await noGL.locator('.hero-poster').isVisible()&&await noGL.locator('.project-card:visible').count()===6,'WebGL failure lost portfolio');
  checks.push('No JavaScript, reduced-motion still image and WebGL failure');
  // Navigate through the UI from the entrance, without teleporting past the obstacle.
  const museum=await fresh({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  await museum.goto(base+'gallery.html');
  await museum.waitForFunction(()=>document.getElementById('loader').classList.contains('done')&&document.querySelectorAll('#worksGrid .card').length>=18,null,{timeout:120000});
  assert(!await museum.locator('#webglFail').isVisible(),'Normal museum load failed');
  assert(await museum.evaluate(()=>window.__MUSEUM.state.hero==='konam'),'Gallery bike did not replace the central exhibit');
  assert(await museum.locator('#selectedProjects a').count()===6,'Gallery project index incomplete');
  assert(await museum.evaluate(()=>window.__MUSEUM.stats.artworkTextures===0),'Museum eagerly loaded every wing artwork');
  await museum.getByLabel('Visual quality').selectOption('balanced');
  assert(await museum.evaluate(()=>window.__MUSEUM.stats.quality==='balanced'),'Quality selection failed');
  await museum.getByLabel('Visual quality').selectOption('auto');
  await museum.getByRole('button',{name:'All works',exact:true}).click();
  await museum.waitForFunction(()=>document.activeElement.id==='worksClose');
  await museum.keyboard.press('Shift+Tab');
  assert(await museum.evaluate(()=>!!document.activeElement.closest('#works')),'Dialog focus escaped backwards: '+await museum.evaluate(()=>document.activeElement.outerHTML.slice(0,300)));
  await museum.keyboard.press('Tab');
  assert(await museum.evaluate(()=>document.activeElement.id==='worksClose'),'Dialog focus failed to wrap');
  await museum.locator('[data-s="eclat"]').click();
  assert(await museum.evaluate(()=>document.body.classList.contains('walking')&&document.getElementById('intro').classList.contains('off')),'Pre-entry tour did not enter');
  const end=await museum.evaluate(async()=>{const layout=await(await fetch('museum/assets/museum_layout.json')).json();const e=layout.exhibits.find(e=>e.slug==='eclat'),a=e.angle*Math.PI/180;return [e.pos[0]-Math.cos(a)*2.6,e.pos[1]-Math.sin(a)*2.6];});
  await museum.waitForFunction(([x,y])=>Math.hypot(window.__MUSEUM.state.x-x,window.__MUSEUM.state.y-y)<.4,end,{timeout:90000});
  await museum.mouse.move(720,450);
  await museum.waitForFunction(()=>window.__MUSEUM.state.target==='eclat',null,{timeout:15000});
  await museum.screenshot({path:'output/playwright/museum-guided-arrival.png'});
  await museum.keyboard.press('e');await museum.waitForSelector('#modal.on');
  const rendersBefore=await museum.evaluate(()=>window.__MUSEUM.stats.renders);
  const before=await museum.evaluate(()=>[window.__MUSEUM.state.x,window.__MUSEUM.state.y]);
  await museum.keyboard.press('w');await museum.waitForTimeout(250);
  const after=await museum.evaluate(()=>[window.__MUSEUM.state.x,window.__MUSEUM.state.y]);
  assert(await museum.evaluate(()=>window.__MUSEUM.stats.renders)===rendersBefore,'Museum rendered behind the dialog');
  assert(Math.hypot(after[0]-before[0],after[1]-before[1])<.01,'Movement continued behind dialog');
  await museum.locator('#m-close').click();await museum.keyboard.press('e');await museum.waitForTimeout(650);
  assert(await museum.locator('#m-frame').getAttribute('src')!=='about:blank','Quickly reopened iframe was cleared');
  checks.push('Quality selection, bounded initial textures and render suspension');
  checks.push('Dialog focus, pre-entry tour, actual route around dais, overlay pause and iframe reopen');
  const lighting=await fresh({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  await lighting.route('**/env_*.hdr',r=>r.abort());
  await lighting.goto(base+'gallery.html');
  await lighting.waitForFunction(()=>document.getElementById('loader').classList.contains('done'),null,{timeout:120000});
  assert(!await lighting.locator('#webglFail').isVisible(),'Optional HDR failure disabled museum');
  await lighting.locator('#enterBtn').click();
  await lighting.getByRole('button',{name:'Works',exact:true}).click();
  assert(await lighting.locator('#worksGrid .card').count()>=18,'HDR failure erased catalogue');
  checks.push('All optional lighting unavailable: museum and catalogue stay usable');
  const missingBike=await fresh({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  await missingBike.route('**/speedmax-*.glb',r=>r.abort());
  await missingBike.goto(base+'gallery.html');
  await missingBike.waitForFunction(()=>document.getElementById('loader').classList.contains('done'),null,{timeout:120000});
  assert(await missingBike.evaluate(()=>window.__MUSEUM.state.hero==='sokai'),'Missing bike did not retain original artwork');
  assert(await missingBike.locator('#selectedProjects a').count()===6,'Missing bike erased project links');
  checks.push('Gallery features bike and case studies; missing bike preserves original katana');
  await museum.locator('#m-close').click();
  const wings=await museum.evaluate(async()=> (await (await fetch('museum/assets/museum_layout.json')).json()).wings);
  for(const wing of wings){await museum.evaluate(w=>window.__MUSEUM.teleport(w.center[0],w.center[1],0),wing);await museum.waitForFunction(key=>window.__MUSEUM.stats.artworkWings.includes(key)&&window.__MUSEUM.stats.artworkTextures>=3,wing.key);assert(await museum.evaluate(()=>window.__MUSEUM.stats.artworkWings.length)<=3,'Artwork wing residency exceeded its budget');assert(await museum.evaluate(()=>window.__MUSEUM.stats.artworkTextures)<=11,'Artwork texture residency exceeded its budget');}
  checks.push('Artwork textures prefetch per wing and remain bounded after all five wings');
  await museum.evaluate(()=>window.__MUSEUM.teleport(0,-5.5,0,.08));
  await museum.mouse.move(720,450);
  await museum.waitForFunction(()=>window.__MUSEUM.state.target==='konam',null,{timeout:15000});
  await museum.screenshot({path:'output/playwright/gallery-bike-atrium.png'});
  await museum.keyboard.press('e');await museum.waitForSelector('#modal.on');
  assert((await museum.locator('#m-frame').getAttribute('src')).includes('projects/konam'),'Bike did not open its project case study');
  checks.push('Central bike opens the Konam project case study');
  for(const c of contexts)await c.close();
  assert(errors.length===0,`Browser errors: ${errors.join('\n')}`);
  return {passed:checks};
}
