from __future__ import annotations
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]; S=R/'site'
h=(S/'observatory.html').read_text(); c=(S/'observatory-v4.css').read_text(); j=(S/'observatory-v4.js').read_text()
health=json.loads((S/'research-health.json').read_text()); patterns=json.loads((S/'pattern-candidates.json').read_text()); review=json.loads((S/'review-queue.json').read_text()); media=json.loads((S/'museum-reference-media.json').read_text()); soc=json.loads((S/'societies.json').read_text()); atlas=json.loads((S/'human-meaning-atlas.json').read_text())
checks=[]
def ck(x,d): checks.append((bool(x),d))
# 1-10 identity/navigation
for x,d in [('Civilization Observatory · NOEMA' in h,'title'),('CIVILIZATION OBSERVATORY · V4' in h,'v4 identity'),('HUMANITY · SPACE × TIME × MEANING' in h,'mission'),('Enter the <em>human story.</em>' in h,'hero'),('aria-label="Primary"' in h,'nav semantics'),(all(x in h for x in ['Explore','Atlas','Compare','Patterns','Review','Research']),'destinations'),('id="commandOpen"' in h,'command'),('id="focusMode"' in h,'focus'),('id="liveStatus"' in h,'live status'),('unknown ≠ absent' in h,'unknown guard')]: ck(x,d)
# 11-20 visual system
for x,d in [('--serif:' in c and '--sans:' in c,'type system'),('Iowan Old Style' in c,'editorial serif'),(all(x in c for x in ['--sand:','--sky:','--rose:','--mint:','--violet:']),'semantic palette'),('.nebula' in c and '.vignette' in c and '.grain' in c,'atmosphere'),('clamp(54px,6.5vw,96px)' in c,'hero scale'),('.epoch-title' in c,'era title'),('.media-ribbon' in c,'media ribbon'),('.pattern-marquee' in c,'pattern marquee'),('@media(max-width:920px)' in c,'tablet'),('@media(max-width:600px)' in c,'mobile')]: ck(x,d)
# 21-30 webgl
for x,d in [('three@0.180.0' in h,'pinned three'),('new THREE.WebGLRenderer' in j,'webgl'),('new THREE.SphereGeometry(1.82,112,112)' in j,'globe detail'),('new THREE.MeshStandardMaterial' in j,'pbr material'),('new THREE.FogExp2' in j,'fog'),('new THREE.HemisphereLight' in j and 'new THREE.DirectionalLight' in j and 'new THREE.PointLight' in j,'lighting'),('new THREE.TorusGeometry' in j,'orbit'),('1500' in j and 'new THREE.Points' in j,'stars'),('pointerdown' in j and 'pointermove' in j and 'wheel' in j,'direct manipulation'),('Math.min(devicePixelRatio,1.8)' in j,'pixel cap')]: ck(x,d)
# 31-40 real world data
for x,d in [('societies.json' in j,'society feed'),('human-meaning-atlas.json' in j,'atlas feed'),(soc.get('actual_size')==100,'100 society benchmark'),(all(x.get('latitude') is not None and x.get('longitude') is not None for x in soc['societies']),'society coordinates'),(len({x['region'] for x in soc['societies']})>=40,'geographic diversity'),(atlas.get('atlas_id')=='NOEMA-HUMAN-MEANING-ATLAS-001','atlas identity'),(len(atlas.get('mapped_events',[]))>0,'dated events'),(all(e.get('site') and e['site'].get('latitude') is not None and e['site'].get('longitude') is not None for e in atlas['mapped_events']),'event coordinates'),(all(e.get('time') and e['time'].get('center_bp') is not None for e in atlas['mapped_events']),'event time'),('latLon(' in j and 'buildDataLayers' in j,'coordinate render')]: ck(x,d)
# 41-50 epistemic geography
for x,d in [('Coverage is not evidence' in h,'coverage guard'),('source-bounded' in h.lower(),'source bounded label'),('D-PLACE coverage' in h,'coverage toggle'),('Dated evidence' in h,'evidence toggle'),('updateEventVisibility' in j,'temporal filter'),('state.currentBP' in j,'time-linked world'),('selectEvent' in j,'event inspect'),('source_url' in j,'source link'),('scope' in j,'scope inspect'),('epistemic_status' in j,'status inspect')]: ck(x,d)
# 51-60 timeline
for x,d in [('id="timeSlider"' in h,'slider'),('300,000 years before present to 2026' in h,'time scope'),('function timeFromSlider' in j,'mapping'),('Deep Pleistocene' in j,'deep era'),('Late Pleistocene' in j,'late era'),('Early Holocene' in j,'holocene'),('Bronze / Iron Age' in j,'bronze iron'),('Historical era' in j,'historical'),('Recent history' in j,'recent'),('does not invent events for empty periods' in j,'empty time guard')]: ck(x,d)
# 61-70 analytics
for x,d in [('pattern-candidates.json' in j,'pattern feed'),(patterns.get('status')=='HYPOTHESIS_GENERATION_ONLY','pattern status'),('q_bh' in j,'q value'),('phi' in j,'effect size'),('lift' in j,'lift'),('n_comparable' in j,'sample size'),('Association only.' in j,'association guard'),('Phylogeny, geography, contact, source dependence and chronology remain unresolved.' in j,'confounders'),('Surface a pattern' in h,'pattern interaction'),('Challenge interpretation' in h,'challenge interaction')]: ck(x,d)
# 71-80 research/review
for x,d in [('research-health.json' in j,'health feed'),(health['metrics']['comparable_profiles']>0,'profiles'),(health['metrics']['accepted_semantic_assertions']>0,'assertions'),('review-queue.json' in j,'review feed'),(review.get('status')=='REVIEW_REQUIRED_NO_AUTOMATIC_PROMOTION','review status'),(all(x['automatic_promotion'] is False for x in review['items']),'no auto promotion'),('26 dimensions' in h,'dimension interface'),(len([x for x in ['Demography','Kinship','Subsistence','Economy','Exchange','Settlement','Governance','Law & norms','Inequality','Conflict','Technology','Mobility','Ancestry','Language','Environment','Health','Cognition','Ritual','Supernatural agents','Myth','Divination & magic','Altered states','Mortuary practices','Symbolism','Institutions','Intergroup contact'] if x in j])==26,'26 dimension model'),('Technology is not migration' in j,'technology guard'),('Language is not ancestry' in j,'language guard')]: ck(x,d)
# 81-90 media/accessibility
for x,d in [('museum-reference-media.json' in j,'media feed'),(media['policy']['not_evidence'] is True,'media not evidence'),(len(media['records'])>0,'media available'),(all(x['rights'] in {'PUBLIC_DOMAIN','CC0'} for x in media['records']),'media rights'),(all(x['evidence_status']=='NOT_EVIDENCE' for x in media['records']),'media epistemics'),('loading="lazy"' in j and 'decoding="async"' in j,'lazy media'),('REFERENCE ONLY' in h,'visible media status'),(':focus-visible' in c,'focus accessibility'),('prefers-reduced-motion' in c and 'state.reduceMotion' in j,'reduced motion'),('WebGL unavailable; data interface remains usable' in j,'webgl fallback')]: ck(x,d)
# 91-100 experience/interaction safety
for x,d in [('Guided journey' in h and 'storyCards' in j,'guided journey'),('JOURNEY 01' in j and 'JOURNEY 04' in j,'journey range'),('metaKey' in j and 'ctrlKey' in j,'keyboard palette'),("e.code==='Space'" in j,'space play'),('/^[1-9]$/.test(e.key)' in j,'lens keys'),('focus-mode' in c,'focus mode css'),('No numeric mechanism probabilities are shown until a calibrated causal model exists.' in h,'no fake causal probability'),('Convergence' in j and 'Preservation bias' in j and 'Unknown' in j,'rival explanations'),('Atmospheric graphics are decorative.' in j,'atmosphere label'),('new THREE.Line' not in j and 'CatmullRomCurve3' not in j,'no invented relationship arcs')]: ck(x,d)
assert len(checks)==100
bad=[]
for n,(ok,d) in enumerate(checks,1):
 print(('PASS' if ok else 'FAIL'),f'V4-{n:03d}',d)
 if not ok: bad.append((n,d))
if bad: raise SystemExit(f'{len(bad)}/100 failed: {bad}')
print('NOEMA OBSERVATORY V4: 100/100 data-native cinematic checks passed')