const demos=[
['cursor-light','01','Cursor Light','A moving pool of warm illumination reveals the bright scene beneath a dark grade.','Move the pointer'],
['cutaway-reveal','02','Cutaway Reveal','A monolithic facade peels back to expose a luminous interior world.','Click anywhere'],
['day-night-morph','03','Moon → Sun','One fixed composition changes state through light, colour and celestial glow.','Click to change state'],
['ambient-spill','04','Ambient Spill','The scene bleeds its palette into the whole viewport, turning the page into emitted light.','Move the pointer'],
['world-transition','05','Shared-Object Transition','A persistent subject survives while the environment accelerates and changes around it.','Click to switch worlds'],
['camera-depth','06','Camera Depth','One generated image is split into depth planes that move at different velocities.','Move the pointer'],
['architectural-type','07','Architectural Type','Oversized typography becomes a physical layer, complete with reflection and parallax.','Move the pointer'],
['theatre-light','08','Theatre Reveal','Warm architectural light activates columns and a distant portal without lifting the foreground blacks.','Click to illuminate'],
['bioluminescence','09','Bioluminescence','Small emissive sources build depth and pathways inside an otherwise dark environment.','Move the pointer'],
['interactive-hud','10','Explorable HUD','Glass UI, a pulsing hotspot and a magnetic action turn a still environment into an explorable interface.','Hover and move']
];
const byId=Object.fromEntries(demos.map(d=>[d[0],d]));
const lobby=window.STUDIO_PLATES?.lobby||'';
const inner=window.STUDIO_PLATES?.innergroup||lobby;
const setBG=(el,img)=>el.style.backgroundImage=`url("${img}")`;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const root=document.documentElement;
function base(){
 const id=document.body.dataset.demo; const d=byId[id];
 document.body.innerHTML=`<main class="lab" id="lab"><div class="ambient"></div><div class="world world-a"></div><div class="world world-b"></div><div class="fx" id="fx"></div><div class="grain"></div><nav class="nav"><a href="../">← Effects Lab</a><span class="pill">${d[1]} / 10</span></nav><section class="copy"><div class="kicker">Studio Motion Study</div><h1>${d[2]}</h1><p>${d[3]}</p></section><div class="hint">${d[4]}</div></main>`;
 const lab=document.getElementById('lab'); setBG(lab.querySelector('.world-a'),lobby); setBG(lab.querySelector('.world-b'),inner); return {id,d,lab,fx:document.getElementById('fx')};
}
function pointerState(lab,cb){let tx=.5,ty=.5,x=.5,y=.5;const tick=()=>{x+=(tx-x)*.085;y+=(ty-y)*.085;lab.style.setProperty('--mx',`${x*100}%`);lab.style.setProperty('--my',`${y*100}%`);lab.style.setProperty('--x',(x-.5).toFixed(4));lab.style.setProperty('--y',(y-.5).toFixed(4));cb?.(x,y);requestAnimationFrame(tick)};addEventListener('pointermove',e=>{tx=e.clientX/innerWidth;ty=e.clientY/innerHeight},{passive:true});tick()}
function clickToggle(lab){addEventListener('click',e=>{if(e.target.closest('a'))return;lab.classList.toggle('active')})}
function initCursor({lab,fx}){lab.style.setProperty('--accent','#ffc97f');lab.querySelector('.world-a').style.filter='brightness(.18) saturate(.6)';const reveal=document.createElement('div');reveal.className='light-reveal';setBG(reveal,lobby);const halo=document.createElement('div');halo.className='light-halo';const cursor=document.createElement('div');cursor.className='cursor-orb';fx.append(reveal,halo,cursor);pointerState(lab)}
function initCutaway({lab,fx}){lab.style.setProperty('--accent','#f0bd73');lab.querySelector('.world-a').style.filter='brightness(.16) grayscale(.15)';const glow=document.createElement('div');glow.className='window-glow';glow.style.setProperty('--plate-inner',`url("${inner}")`);const facade=document.createElement('div');facade.className='facade';for(let i=0;i<9;i++){const s=document.createElement('div');s.className='slab';facade.appendChild(s)}fx.append(glow,facade);clickToggle(lab);pointerState(lab)}
function initDayNight({lab,fx}){lab.style.setProperty('--accent','#a7cbff');lab.style.setProperty('--ambient','#0d284a');lab.querySelector('.world-a').style.filter='brightness(.48) saturate(.72) hue-rotate(8deg)';const celestial=document.createElement('div');celestial.className='moon-sun';const horizon=document.createElement('div');horizon.className='horizon';fx.append(horizon,celestial);clickToggle(lab);lab.addEventListener('click',()=>{lab.style.setProperty('--accent',lab.classList.contains('active')?'#ffad4f':'#a7cbff');lab.style.setProperty('--ambient',lab.classList.contains('active')?'#7d1909':'#0d284a')});pointerState(lab)}
function initAmbient({lab}){lab.style.setProperty('--accent','#e6b170');lab.style.setProperty('--ambient','#372013');const a=lab.querySelector('.world-a');a.style.filter='brightness(.66) saturate(.92)';pointerState(lab,(x,y)=>{const hue=Math.round(18+x*190);lab.style.setProperty('--accent',`hsl(${hue} 72% 66%)`);lab.style.setProperty('--ambient',`hsl(${hue} 58% 18%)`);a.style.transform=`translate3d(${(x-.5)*-18}px,${(y-.5)*-11}px,0) scale(1.07)`})}
function initWorld({lab,fx}){lab.style.setProperty('--accent','#cde8ff');const a=lab.querySelector('.world-a'),b=lab.querySelector('.world-b');a.style.filter='brightness(.62) saturate(.9) sepia(.18)';b.style.filter='brightness(.64) saturate(.82) hue-rotate(165deg)';const obj=document.createElement('div');obj.className='persistent-object';obj.innerHTML='<i></i><b></b>';const streaks=document.createElement('div');streaks.className='streaks';fx.append(streaks,obj);let second=false;addEventListener('click',e=>{if(e.target.closest('a'))return;lab.classList.add('switching');setTimeout(()=>{second=!second;a.style.opacity=second?'0':'1';b.style.opacity=second?'1':'0';lab.style.setProperty('--accent',second?'#9af6ff':'#ffd29a');lab.style.setProperty('--ambient',second?'#062737':'#4a240f')},260);setTimeout(()=>lab.classList.remove('switching'),820)});pointerState(lab)}
function initDepth({lab,fx}){lab.style.setProperty('--accent','#efc58e');lab.querySelector('.world-a').style.opacity='0';for(const c of ['back','mid','front']){const l=document.createElement('div');l.className=`depth-layer ${c}`;setBG(l,c==='front'?inner:lobby);fx.appendChild(l)}pointerState(lab)}
function initType({lab,fx}){lab.style.setProperty('--accent','#f6d09c');lab.querySelector('.world-a').style.filter='brightness(.5) contrast(1.08)';const type=document.createElement('div');type.className='mega-type';type.dataset.text='ATRIUM';type.textContent='ATRIUM';fx.appendChild(type);pointerState(lab,(x,y)=>{type.style.transform=`translate3d(${(x-.5)*22}px,${(y-.5)*10}px,0)`})}
function initTheatre({lab,fx}){lab.style.setProperty('--accent','#83a9d8');lab.style.setProperty('--ambient','#071522');lab.querySelector('.world-a').style.filter='brightness(.11) saturate(.5)';const columns=document.createElement('div');columns.className='columns';for(let i=0;i<7;i++){const c=document.createElement('div');c.className='column';c.style.height=`${58+(i%3)*9}%`;columns.appendChild(c)}const strip=document.createElement('div');strip.className='ceiling-strip';const portal=document.createElement('div');portal.className='portal';fx.append(columns,strip,portal);clickToggle(lab);lab.addEventListener('click',()=>{const on=lab.classList.contains('active');lab.style.setProperty('--accent',on?'#ffc07a':'#83a9d8');lab.style.setProperty('--ambient',on?'#542006':'#071522')});pointerState(lab)}
function initBio({lab,fx}){lab.style.setProperty('--accent','#62ffe2');lab.style.setProperty('--ambient','#062a24');lab.querySelector('.world-a').style.filter='brightness(.12) saturate(.48) hue-rotate(18deg)';const field=document.createElement('div');field.className='bio-field';for(let i=0;i<42;i++){const s=document.createElement('i');s.className='spore';const size=4+Math.random()*13;s.style.setProperty('--s',`${size}px`);s.style.setProperty('--d',`${2.5+Math.random()*5}s`);s.style.left=`${8+Math.random()*86}%`;s.style.top=`${22+Math.random()*68}%`;s.style.opacity=.35+Math.random()*.65;field.appendChild(s)}for(let i=0;i<14;i++){const m=document.createElement('i');m.className='mushroom';m.style.left=`${12+Math.random()*78}%`;m.style.top=`${56+Math.random()*33}%`;m.style.transform=`scale(${.45+Math.random()*.9})`;field.appendChild(m)}fx.appendChild(field);pointerState(lab,(x,y)=>{field.style.transform=`translate3d(${(x-.5)*-10}px,${(y-.5)*-6}px,0)`})}
function initHud({lab,fx}){lab.style.setProperty('--accent','#e1bd89');lab.querySelector('.world-a').style.filter='brightness(.55) saturate(.85)';const p=document.createElement('div');p.className='glass-panel';p.innerHTML='<small>Spatial index 03</small><h2>Enter the quiet room.</h2><p>Hover the action, move around the environment and use the hotspot as an invitation to explore rather than a conventional button.</p><a class="magnetic" href="#">Explore detail →</a>';const h=document.createElement('div');h.className='hotspot';fx.append(p,h);const btn=p.querySelector('.magnetic');addEventListener('pointermove',e=>{const r=btn.getBoundingClientRect();const dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);const dist=Math.hypot(dx,dy);btn.style.setProperty('--bx',dist<110?`${clamp(dx*.16,-14,14)}px`:'0px');btn.style.setProperty('--by',dist<110?`${clamp(dy*.16,-10,10)}px`:'0px')},{passive:true});pointerState(lab)}
function initIndex(){document.body.className='index-page';document.body.innerHTML=`<div class="kicker">Caldas Studio / Effects Lab</div><h1>Motion as<br>architecture.</h1><p>Ten isolated prototypes rebuilt from the interaction grammar in the reference recording. All imagery is sourced from the locally embedded ChatGPT-generated Studio plates; each study changes the mechanics rather than copying the original art direction.</p><div class="grid">${demos.map((d,i)=>`<a class="card" href="./${d[0]}/"><div class="card-bg"></div><span>${d[1]} / 10</span><h2>${d[2]}</h2><p>${d[3]}</p></a>`).join('')}</div>`;document.querySelectorAll('.card-bg').forEach((b,i)=>setBG(b,i%2?inner:lobby))}
const demo=document.body.dataset.demo;
if(!demo||demo==='index')initIndex();else{const ctx=base();({
'cursor-light':initCursor,'cutaway-reveal':initCutaway,'day-night-morph':initDayNight,'ambient-spill':initAmbient,'world-transition':initWorld,'camera-depth':initDepth,'architectural-type':initType,'theatre-light':initTheatre,'bioluminescence':initBio,'interactive-hud':initHud
}[demo]||(()=>{}))(ctx)}