import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';

const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const index=read('index.html'), bellagio=read('bellagio.html'), login=read('login.html'), loginJs=read('login.js'), mw=read('middleware.js'), session=read('api/session.js'), asset=read('api/asset.js'), sourceHealth=read('api/source-health.js'), benchmarkApi=read('api/benchmark.js'), evidenceClient=read('runtime/evidence.js'), benchmarkMigration=read('supabase/migrations/20261006080500_spatial_benchmarks_owner_evidence.sql'), benchmarkGrantHardening=read('supabase/migrations/20261006081000_harden_spatial_benchmark_grants.sql'), xrBenchmarkMigration=read('supabase/migrations/20261006082300_spatial_benchmark_xr_session_fields.sql'), vercel=JSON.parse(read('vercel.json')), scene=JSON.parse(read('worlds/bellagio-lobby.scene.json')), worldZero=JSON.parse(read('worlds/world-zero.scene.json')), registry=JSON.parse(read('worlds/registry.json'));

for(const [name,html] of [['world-zero',index],['bellagio',bellagio],['login',login]]){
  assert.match(html,/width=device-width,initial-scale=1,viewport-fit=cover/,name+' viewport contract');
  assert.doesNotMatch(html,/width:\s*100vw/,name+' must not force 100vw');
}
for(const [name,html] of [['world-zero',index],['bellagio',bellagio]]){
  assert.match(html,/@media\(max-width:760px\)/,name+' phone reflow');
  assert.match(html,/@media\(max-height:500px\) and \(orientation:landscape\)/,name+' short-landscape reflow');
  assert.match(html,/VRButton\.createButton/,name+' WebXR entry');
  for(const id of ['fps','draws','tris','dpr','p95'])assert.match(html,new RegExp('id="'+id+'"'),name+' telemetry '+id);
  assert.match(html,/SAFE FALLBACK/,name+' safe fallback');
}
assert.match(index,/href="\/bellagio\.html"/,'World Zero routes to Bellagio benchmark');
assert.match(index,/href="\/diagnostics\.html"/,'World Zero routes to device diagnostics');
const diagnostics=read('diagnostics.html'), evidencePage=read('evidence.html'), benchmark=read('runtime/benchmark.js'), qualityCore=read('runtime/quality.js'), xrCore=read('runtime/xr-interactions.js');
assert.match(diagnostics,/navigator\.gpu/,'diagnostics checks WebGPU');
assert.match(diagnostics,/isSessionSupported\('immersive-vr'\)/,'diagnostics checks immersive WebXR');
assert.match(diagnostics,/MAX_TEXTURE_SIZE/,'diagnostics inspects GPU limits');
assert.doesNotMatch(diagnostics,/fetch\(|XMLHttpRequest/,'diagnostics stays local-only');
assert.match(diagnostics,/\?benchmark=screen/,'diagnostics exposes screen benchmark links');
assert.match(diagnostics,/\?benchmark=xr/,'diagnostics exposes immersive XR benchmark links');
assert.doesNotMatch(diagnostics,/\?benchmark=1/,'diagnostics must not expose ambiguous benchmark mode');
assert.match(diagnostics,/href="\/evidence\.html"/,'diagnostics links owner evidence');
assert.match(evidencePage,/fetch\('\/api\/benchmark'/,'evidence page reads only same-origin owner endpoint');
assert.match(evidencePage,/x\.xr_active/,'evidence page displays actual immersive-session flag');
assert.match(evidencePage,/x\.xr_frame_rate/,'evidence page displays session-reported XR frame rate');
assert.doesNotMatch(evidencePage,/x\.(?:user_id|email|ip_address|user_agent|latitude|longitude)/,'evidence page renders no direct personal-identifier fields');
assert.match(evidencePage,/No benchmark receipts yet/,'evidence page starts honestly empty');
assert.doesNotMatch(evidencePage,/dummy|fixture|seed/i,'evidence page contains no synthetic benchmark rows');
assert.match(index,/benchmarkRequested/,'World Zero supports benchmark mode');
assert.match(bellagio,/benchmarkRequested/,'Bellagio supports benchmark mode');
assert.match(index,/benchmarkMode==='xr'&&!renderer\.xr\.isPresenting/,'World Zero XR benchmark waits for immersive session');
assert.match(bellagio,/benchmarkMode==='xr'&&!renderer\.xr\.isPresenting/,'Bellagio XR benchmark waits for immersive session');
assert.match(index,/sessionstart.*startBenchmark/s,'World Zero XR benchmark starts from XR session event');
assert.match(bellagio,/sessionstart.*startBenchmark/s,'Bellagio XR benchmark starts from XR session event');
assert.match(index,/if\(benchActive\|\|qualityMode/,'World Zero freezes adaptive quality while measuring');
assert.match(bellagio,/if\(benchActive\|\|qualityMode/,'Bellagio freezes adaptive quality while measuring');
assert.match(index,/xr_active:benchContext\.xrActive/,'World Zero receipt records active immersive state');
assert.match(bellagio,/xr_active:benchContext\.xrActive/,'Bellagio receipt records active immersive state');
assert.match(index,/xr_frame_rate:benchContext\.xrFrameRate/,'World Zero receipt records XR frame rate when exposed');
assert.match(bellagio,/xr_frame_rate:benchContext\.xrFrameRate/,'Bellagio receipt records XR frame rate when exposed');
assert.match(index,/summarizeFrames/,'World Zero uses shared benchmark core');
assert.match(bellagio,/summarizeFrames/,'Bellagio uses shared benchmark core');
assert.match(index,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/,'World Zero mobile telemetry is width-safe');
assert.match(index,/\[hidden\]\{display:none!important\}/,'World Zero hidden attribute cannot be overridden');
assert.match(bellagio,/\[hidden\]\{display:none!important\}/,'Bellagio hidden attribute cannot be overridden');
assert.match(index,/@media\(max-height:500px\) and \(orientation:landscape\).*?\.controls>\*\{width:auto/s,'World Zero short landscape cancels phone full-width controls');
assert.match(bellagio,/@media\(max-height:500px\) and \(orientation:landscape\).*?\.actions>\*\{width:auto/s,'Bellagio short landscape cancels phone full-width controls');
assert.doesNotMatch(index,/function available\(/,'World Zero must not create a throwaway WebGL probe context');
assert.doesNotMatch(bellagio,/function available\(/,'Bellagio must not create a throwaway WebGL probe context');
assert.match(index,/new THREE\.WebGLRenderer[\s\S]*?catch\(error\)/,'World Zero renderer init is the capability gate');
assert.match(bellagio,/new THREE\.WebGLRenderer[\s\S]*?catch\(error\)/,'Bellagio renderer init is the capability gate');
assert.match(bellagio,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/,'Bellagio mobile telemetry is width-safe');
assert.match(bellagio,/function cropGeometry\(/,'Bellagio benchmark crops the shared baked mesh by room bounds');
assert.match(bellagio,/LOBBY_BOUNDS/,'Bellagio benchmark uses semantic lobby bounds');
assert.match(bellagio,/function chihuly\(/,'Bellagio reuses its canonical Fiori di Como generator');
assert.match(bellagio,/LOCAL_TARGET/,'Bellagio OrbitControls use local coordinates under the XR origin rig');
assert.match(index,/createXRInteractionSystem/,'World Zero uses shared XR interaction core');
assert.match(bellagio,/createXRInteractionSystem/,'Bellagio uses shared XR interaction core');
assert.match(xrCore,/selectstart/,'XR core uses standard select interaction');
assert.match(xrCore,/getController\(index\)/,'XR core uses WebXR target-ray abstraction for controllers or hands');
assert.match(index,/location\.assign\(route\)/,'World Zero has a navigable XR portal');
assert.match(index,/registerBikeInteraction/,'Speedmax is XR-selectable');
assert.match(bellagio,/WORLD ZERO/,'Bellagio includes XR return portal');
assert.doesNotMatch(xrCore,/navigator\.userAgent|Quest|Oculus|Meta Quest/i,'XR core does not device-sniff');
assert.equal(scene.semantic_authority,'mesh');
assert.ok(scene.assets.some(a=>a.role==='semantic-mesh'&&a.bytes===3950912));
assert.ok(scene.excluded_from_r0.some(a=>a.path==='assets/city.glb'&&a.bytes===11940384));
assert.equal(scene.source.revision,'b13ece357ddf46086acfec0966a4f63a947f29f3');
assert.equal(registry.schema,'caldas.world-registry/v0');
assert.equal(new Set(registry.worlds.map(w=>w.id)).size,registry.worlds.length,'world ids unique');
assert.equal(new Set(registry.worlds.map(w=>w.route)).size,registry.worlds.length,'world routes unique');
assert.ok(registry.worlds.some(w=>w.id==='room:spatial-lab:bellagio-lobby-r0'&&w.scene_manifest==='worlds/bellagio-lobby.scene.json'));
assert.ok(registry.worlds.every(w=>typeof w.scene_manifest==='string'&&w.scene_manifest.length>0),'every registered scene has a manifest');
assert.equal(worldZero.schema,'caldas.scene/v0');
assert.equal(worldZero.assets[0].delivery.id,'speedmax');
assert.equal(worldZero.benchmark_policy.upload,true,'World Zero benchmark persistence is enabled');
assert.equal(worldZero.benchmark_policy.persistence,'owner-scoped-supabase-rls','World Zero benchmark persistence is owner-scoped through RLS');
assert.deepEqual(worldZero.benchmark_policy.modes,['screen','xr']);
assert.equal(worldZero.benchmark_policy.adaptive_quality_during_measurement,false);
assert.deepEqual(scene.benchmark_policy.modes,['screen','xr']);
assert.equal(scene.benchmark_policy.adaptive_quality_during_measurement,false);
assert.doesNotMatch(loginJs,/localStorage|sessionStorage/,'auth token must not use browser storage');
assert.match(login,/id="recover"/,'password recovery is visible');
assert.match(loginJs,/https:\/\/joaoccaldas\.github\.io\/konam\/index\.html/,'recovery reuses canonical KONA callback');
for(const token of ['HttpOnly','Secure','SameSite=Lax'])assert.match(session,new RegExp(token),'session cookie '+token);
assert.match(session,/a0468c5f-ea3c-4e59-9c7f-201c0131bea9/,'owner UUID allowlist');
assert.match(mw,/PUBLIC=new Set\(\['\/login\.html'/,'explicit public allowlist');
assert.doesNotMatch(mw,/PUBLIC[^\n]*'\/'/,'world root must not be public');
const csp=vercel.headers[0].headers.find(h=>h.key==='Content-Security-Policy')?.value||'';
assert.ok(csp&&!csp.includes('*'),'CSP must exist without wildcard');
assert.match(csp,/frame-ancestors 'none'/);
assert.doesNotMatch(csp,/raw\.githubusercontent\.com/,'browser CSP must not contact raw GitHub directly');
assert.match(index,/BIKE='\/api\/asset\?id=speedmax'/,'Speedmax uses same-origin gateway');
assert.match(bellagio,/ASSET=id=>'\/api\/asset\?id='/,'Bellagio uses same-origin gateway');
assert.match(asset,/Object\.freeze\(\{/,'asset gateway is a closed allowlist');
assert.match(asset,/expectedBytes:2081248/,'Speedmax byte identity pinned');
assert.match(asset,/expectedBytes:3950912/,'Bellagio GLB byte identity pinned');
assert.doesNotMatch(asset,/req\.query/,'asset route does not rely on framework query helpers');
assert.match(sourceHealth,/speedmax/,'source health covers Speedmax');
assert.match(sourceHealth,/bellagio/,'source health covers Bellagio');
assert.match(mw,/\/api\/source-health/,'source health is explicitly public');
assert.doesNotMatch(mw,/PUBLIC[^\n]*\/api\/asset/,'asset bytes stay behind auth');

function inlineModule(html){
  const matches=[...html.matchAll(/<script type="module">(.*?)<\/script>/gs)];
  assert.equal(matches.length,1,'expected exactly one inline module');
  return matches[0][1].replace(/^import .*?;\s*$/gm,'');
}
for(const [name,html] of [['world-zero',index],['bellagio',bellagio]]){
  try{new Function(inlineModule(html));}catch(e){throw new Error(name+' inline JS parse failed: '+e.message);}
}
const qmod=await import(new URL('../runtime/quality.js',import.meta.url));
const bmod=await import(new URL('../runtime/benchmark.js',import.meta.url));
assert.equal(qmod.percentile95([10,20,30,40,50]),50,'p95 deterministic');
assert.equal(qmod.nextAutoDpr({p95:25,current:1.25,cap:1.25}),1.15,'slow frame reduces DPR');
assert.equal(qmod.nextAutoDpr({p95:12,current:1.0,cap:1.25}),1.05,'fast frame cautiously raises DPR');
assert.equal(qmod.qualityProfile('auto',{coarse:true,cores:8,memory:8,short:800}).tier,'balanced','coarse device starts balanced');
assert.equal(qmod.qualityProfile('auto',{coarse:false,cores:8,memory:8,short:900,caps:{high:1.55}}).dpr,1.55,'scene DPR cap overrides generic high');
const br=bmod.summarizeFrames([16,16,17,20]);
assert.equal(br.samples,4); assert.ok(br.approxFps>55&&br.approxFps<65); assert.equal(br.p95Ms,20);
assert.doesNotMatch(benchmark,/fetch\(|XMLHttpRequest/,'benchmark core is pure/local');
assert.doesNotMatch(qualityCore,/fetch\(|XMLHttpRequest/,'quality core is pure/local');
assert.match(index,/persistBenchmark/,'World Zero persists benchmark evidence');
assert.match(bellagio,/persistBenchmark/,'Bellagio persists benchmark evidence');
assert.match(evidenceClient,/fetch\('\/api\/benchmark'/,'evidence client uses same-origin benchmark endpoint');
assert.doesNotMatch(evidenceClient,/service[_-]?role/i,'evidence client has no service-role credential');
assert.match(benchmarkApi,/VERCEL_GIT_COMMIT_SHA/,'server owns release identity');
assert.match(benchmarkApi,/OWNER_ID/,'server verifies owner identity');
assert.match(benchmarkApi,/spatial_token/,'server reads only HttpOnly session cookie');
assert.match(benchmarkApi,/rest\/v1\/spatial_benchmarks/,'server writes through Supabase RLS path');
assert.match(benchmarkApi,/req\.method==='GET'/,'benchmark API supports owner-scoped reads');
assert.match(benchmarkApi,/xr_active:body\.xr_active===true/,'benchmark API validates immersive XR flag');
assert.match(benchmarkApi,/xr_frame_rate:body\.xr_frame_rate==null\?null:finite/,'benchmark API validates XR frame rate');
assert.doesNotMatch(benchmarkApi,/email|user_agent|user agent|ip_address/i,'benchmark API does not persist direct personal identifiers');
assert.doesNotMatch(benchmarkApi,/service[_-]?role/i,'benchmark API has no service-role credential');
assert.match(benchmarkMigration,/enable row level security/i,'benchmark table enables RLS');
assert.match(benchmarkMigration,/force row level security/i,'benchmark table forces RLS');
assert.match(benchmarkMigration,/grant select, insert on table public\.spatial_benchmarks to authenticated/i,'benchmark table grants only read+insert to authenticated');
assert.doesNotMatch(benchmarkMigration,/grant .*update|grant .*delete/i,'benchmark migration grants no update/delete');
assert.match(benchmarkGrantHardening,/revoke all on table public\.spatial_benchmarks from authenticated/i,'hardening revokes Supabase default authenticated grants');
assert.match(benchmarkGrantHardening,/grant select, insert on table public\.spatial_benchmarks to authenticated/i,'hardening restores only select+insert');
assert.doesNotMatch(benchmarkGrantHardening,/grant .*update|grant .*delete|grant .*truncate/i,'hardening grants no mutation beyond insert');
assert.match(xrBenchmarkMigration,/add column xr_active boolean not null default false/i,'XR migration stores actual immersive state');
assert.match(xrBenchmarkMigration,/add column xr_frame_rate numeric/i,'XR migration stores reported session frame rate');
assert.match(xrBenchmarkMigration,/xr_frame_rate >= 30/i,'XR frame rate is bounded');
const health=read('api/health.js');
assert.match(health,/VERCEL_GIT_COMMIT_SHA/,'health exposes deployed SHA');
assert.match(health,/bellagio-lobby-r0/,'health lists Bellagio benchmark');
for(const file of ['login.js','middleware.js','api/session.js','api/logout.js','api/health.js','api/asset.js','api/source-health.js','api/benchmark.js','runtime/evidence.js','runtime/xr-interactions.js']){
  const r=spawnSync(process.execPath,['--check',new URL('../'+file,import.meta.url).pathname],{encoding:'utf8'});
  assert.equal(r.status,0,file+' node syntax: '+r.stderr);
}
console.log('Spatial Lab contract PASS: auth, source pinning, scene authority, responsive rules, XR/fallback telemetry and JS syntax.');
