#!/usr/bin/env python3
"""Build src/catalog.js from the public ridewyld.com Shopify product feed.

    python3 tools/sync_catalog.py                 # fetch live feed
    python3 tools/sync_catalog.py products.json   # use a saved feed

Keeps real handles, prices, variant ids (for cart permalinks) and CDN images.
Private team kits (Synergy Sport Collective) are left out of the retail shop.
"""
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

FEED = "https://ridewyld.com/products.json?limit=250"
OUT = Path(__file__).resolve().parent.parent / "src" / "catalog.js"
EXCLUDE_TAGS = {"SSC"}


def load(argv):
    if len(argv) > 1:
        return json.loads(Path(argv[1]).read_text())
    req = urllib.request.Request(FEED, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def category(p):
    tags = {t.lower() for t in p["tags"]}
    kind = (p["product_type"] or "").lower()
    if "trisui" in p["handle"] or any("trisui" in t for t in tags):
        return "triathlon", "Trisuit"
    if "run wyld" in tags:
        return "run", p["product_type"] or "Run"
    if "accessories" in tags or kind in {"cap", "ear plugs", "gift cards"}:
        return "accessories", p["product_type"] or "Accessory"
    if "bib" in kind:
        return "cycling", "Bib Shorts"
    if "gilet" in kind:
        return "cycling", "Gilet"
    if "club cut" in kind:
        return "cycling", "Club Fit Jersey"
    return "cycling", "Race Fit Jersey"


def clean_title(t):
    t = re.sub(r"\s*\|\s*(Race|Club) Fit$", "", t)
    return re.sub(r"^WYLD\s+(?!GIFT)", "", t).replace("WYLD GIFT CARD", "Gift Card")


def paragraphs(body):
    body = re.sub(r"<h\d[^>]*>.*?</h\d>", "", body or "", flags=re.S)
    out = []
    for p in re.findall(r"<p[^>]*>(.*?)</p>", body, flags=re.S):
        text = re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", p))).strip()
        if len(text) > 40:
            out.append(text)
    return out[:3]


def img(src):
    # Serve every image from the store's own CDN path: /cdn/shop/{files|products}/...
    path = src.split("?")[0]
    path = re.sub(r"^https://cdn\.shopify\.com/s/files/\d+/\d+/\d+/\d+/", "/cdn/shop/", path)
    return path.replace("https://ridewyld.com", "")


def main(argv):
    products = []
    for p in load(argv)["products"]:
        if EXCLUDE_TAGS & set(p["tags"]):
            continue
        cat, kind = category(p)
        opts = [{"name": o["name"], "values": o["values"]} for o in p["options"]]
        if opts and opts[0]["name"] == "Valörer":
            opts[0]["name"] = "Amount"
        variants = [
            {
                "id": v["id"],
                "o": [x for x in (v["option1"], v["option2"], v["option3"]) if x],
                "price": float(v["price"]),
                "was": float(v["compare_at_price"]) if v["compare_at_price"] else None,
                "ok": v["available"],
            }
            for v in p["variants"]
        ]
        prices = [v["price"] for v in variants]
        was = [v["was"] for v in variants if v["was"] and v["was"] > v["price"]]
        styles = next((o["values"] for o in opts if o["name"] == "Style"), [])
        products.append(
            {
                "handle": p["handle"],
                "title": clean_title(p["title"]),
                "category": cat,
                "kind": kind,
                "price": min(prices),
                "was": max(was) if was else None,
                "from": len(set(prices)) > 1,
                "available": any(v["ok"] for v in variants),
                "women": "Female" in styles or "women" in {t.lower() for t in p["tags"]},
                "men": "Male" in styles or "men" in {t.lower() for t in p["tags"]},
                "images": [img(i["src"]) for i in p["images"]][:6],
                "options": opts,
                "variants": variants,
                "copy": paragraphs(p["body_html"]),
            }
        )
    OUT.write_text(
        "// Generated by tools/sync_catalog.py from the public ridewyld.com feed.\n"
        "export const catalog = " + json.dumps(products, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    print(f"{len(products)} products -> {OUT}")


if __name__ == "__main__":
    main(sys.argv)
